# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.3.9-cli-stretch-node

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Restore Composer cache
      - restore_cache:
          keys:
            - composer-dependencies-{{ checksum "composer.json" }}
            - composer-dependencies-

      # Execute Composer install
      - run:
          command: composer --no-interaction --optimize-autoloader install
          environment:
            PRIVATE_KEY: abc123

      # Save Composer cache
      - save_cache:
          paths:
            - ./vendor
          key: composer-dependencies-{{ checksum "composer.json" }}

      # Restore Yarn cache
      - restore_cache:
          keys:
            - yarn-dependencies-{{ checksum "package.json" }}

      # Execute Yarn install and build
      - run: yarn install
      - run:
          command: ./scripts/build.sh
          environment:
            PRIVATE_KEY: abc123

      # Save Yarn cache
      - save_cache:
          paths:
            - ./node_modules
          key: yarn-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          command: ./vendor/bin/phpunit
          environment:
            PRIVATE_KEY: abc123
